### ISSUE TITLE
Google Cloud API Client initialization inconsistent

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/ruby-docs-samples#52] opened 2016-09-16 17:57 UTC
**Story**

Rubyist knows to use **Google Data Store API**. Rubyist wants to learn **Google Vision API** and the samples use different **Google Cloud API Client** initialization. _Confusion begins_.

**Issue**
Initialization is inconsistent between these two samples. The issue may exist in other samples within the Ruby space. 

_DataStore uses_
require "gcloud"
gcloud = Gcloud.new
datastore = gcloud.datastore

_Vision uses_
require "google/cloud"
gcloud = Google::Cloud.new
vision = gcloud.vision

**Issue exists in the following locations:**
appengine/datastore/app.rb
appengine/pubsub/app.rb
appengine/pubsub/spec/pubsub_spec.rb
bigquery/shakespeare.rb
datastore/sample.rb
logging/spec/sample_spec.rb
logging/sample.rb
pubsub/sample.rb

**Possible Solution**
Use the same initialization in all Ruby samples.

**Comment by remi** [comment] 2016-09-26 20:26
Duplicate of #55 

Fix pending in #65

**Closed by remi** 2016-09-26 20:26 UTC
