### ISSUE TITLE
Memcache sample deprecated and not working

### ISSUE THREAD

**Issue by aamatte** [GoogleCloudPlatform/ruby-docs-samples#162] opened 2017-04-11 13:47 UTC
The [`app.yaml`](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/appengine/memcache/app.yaml) configuration file uses `vm: true`, which [is deprecated](https://cloud.google.com/appengine/docs/flexible/python/upgrading). Also, the memcache service is currently not available for the App Engine flexible environment according to [this](https://cloud.google.com/appengine/docs/flexible/python/upgrading#memcache_service).

**Comment by aamatte** [comment] 2017-04-11 19:22
Nope, not working. After running `gcloud app deploy` it fails with the following error:
```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Deployments to App Engine Flexible require `env: flex` in app.yaml.  The `vm:true` setting has been deprecated.
To learn more, please visit https://cloud.google.com/appengine/docs/flexible/python/upgrading.
```

**Comment by frankyn** [comment] 2017-12-11 22:45
Closing comment as it's intended behavior as Memcache is not available for GAE flexible environment.

**Closed by frankyn** 2017-12-11 22:45 UTC
